post_install() {
    gtk-update-icon-cache -f -t "/usr/share/icons/hicolor"
    update-desktop-database "/usr/share/applications"
    update-mime-database "/usr/share/mime"
}
pre_upgrade() {
}
post_upgrade() {
    post_install
}
pre_remove() {
}
post_remove() {
    gtk-update-icon-cache -f -t "/usr/share/icons/hicolor"
    update-desktop-database "/usr/share/applications"
    update-mime-database "/usr/share/mime"
}