import os
import sys
import subprocess
import tempfile
import shutil
import time
import shlex
import re
from pathlib import Path

def get_deb_info(tmpdir):
    """Extrae información del archivo control de un .deb"""
    info = {
        'name': '',
        'version': '1.0',
        'description': 'Converted by Wakka',
        'size': '0',
        'arch': 'x86_64'
    }
    
    control_path = os.path.join(tmpdir, "control")
    if not os.path.exists(control_path):
        # Intentar extraer control.tar.*
        for f in os.listdir(tmpdir):
            if f.startswith("control.tar"):
                subprocess.run(["tar", "-xf", os.path.join(tmpdir, f), "-C", tmpdir], check=False)
                break
    
    if os.path.exists(control_path):
        with open(control_path, "r", errors='ignore') as f:
            for line in f:
                if ":" in line:
                    parts = line.split(":", 1)
                    if len(parts) < 2: continue
                    key, val = [x.strip() for x in parts]
                    key = key.lower()
                    if key == "package": info['name'] = val
                    elif key == "version": info['version'] = val.replace("-", "_")
                    elif key == "description": info['description'] = val
                    elif key == "installed-size": info['size'] = str(int(val) * 1024)
                    elif key == "architecture":
                        if val == "amd64": info['arch'] = "x86_64"
                        elif val == "i386": info['arch'] = "i686"
                        else: info['arch'] = "any"
    return info

def convert_to_arch(file_path):
    file_path = os.path.abspath(file_path)
    ext = Path(file_path).suffix.lower()
    
    with tempfile.TemporaryDirectory() as tmpdir:
        input_tmp = os.path.join(tmpdir, "input")
        output_tmp = os.path.join(tmpdir, "output")
        os.makedirs(input_tmp)
        os.makedirs(output_tmp)
        
        os.chdir(input_tmp)
        print(f"--- Extracting {file_path} ---")
        
        if ext == ".deb":
            subprocess.run(["ar", "x", file_path], check=True)
            data_tar = next((f for f in os.listdir(".") if f.startswith("data.tar")), None)
            if not data_tar:
                print("Error: data.tar not found")
                return None
            subprocess.run(["tar", "-xf", data_tar, "-C", output_tmp], check=True)
            info = get_deb_info(input_tmp)
        else:
            subprocess.run(["bsdtar", "-xf", file_path, "-C", output_tmp], check=True)
            info = {
                'name': Path(file_path).stem.lower().replace("_", "-"),
                'version': '1.0',
                'description': 'Converted by Wakka',
                'size': '0',
                'arch': 'x86_64'
            }

        if not info['name']:
            info['name'] = Path(file_path).stem.lower().replace("_", "-")

        os.chdir(output_tmp)
        subprocess.run("find . -type f | sed -e 's/^\\.\\///' > .FILELIST", shell=True, check=True)
        
        pkginfo_path = ".PKGINFO"
        with open(pkginfo_path, "w") as f:
            f.write(f"# Generated by Wakka (Alien logic)\n")
            f.write(f"pkgname = {info['name']}\n")
            f.write(f"pkgver = {info['version']}-1\n")
            f.write(f"pkgdesc = {info['description']}\n")
            f.write(f"arch = {info['arch']}\n")
            f.write(f"license = unknown\n")
            f.write(f"builddate = {int(time.time())}\n")
            f.write(f"packager = Wakka\n")
            if info['size'] != '0':
                f.write(f"size = {info['size']}\n")

        output_name = f"{info['name']}-{info['version']}-1-{info['arch']}.pkg.tar.zst"
        output_path = os.path.join("/tmp", output_name)
        
        print(f"--- Creating Arch package: {output_path} ---")
        files_to_add = [".PKGINFO", ".FILELIST"]
        for item in os.listdir("."):
            if item not in files_to_add:
                files_to_add.append(item)
                
        subprocess.run(["tar", "-c", "-I", "zstd", "-f", output_path] + files_to_add, check=True)
        return output_path

def install_appimage(file_path):
    file_path = os.path.abspath(file_path)
    # Nombre base limpio
    raw_name = Path(file_path).stem.lower().split("_")[0].split("-")[0]
    opt_dir = Path("/opt") / raw_name
    opt_dir.mkdir(parents=True, exist_ok=True)
    
    target_path = opt_dir / f"{raw_name}.AppImage"
    shutil.copy2(file_path, target_path)
    target_path.chmod(0o755)
    
    # Metadatos por defecto
    app_name = raw_name.capitalize()
    description = "Application installed via Wakka"
    icon_source = "utilities-terminal"
    
    # Intentar extraer metadatos
    try:
        with tempfile.TemporaryDirectory() as tmpdir:
            res = subprocess.run([target_path, "--appimage-offset"], capture_output=True, text=True, timeout=5)
            offset = res.stdout.strip() if res.returncode == 0 else "0"
            
            extract_dir = Path(tmpdir) / "squashfs-root"
            # Extraer TODO el contenido para no perder iconos en subcarpetas
            subprocess.run(["unsquashfs", "-o", offset, "-d", str(extract_dir), "-f", str(target_path)], capture_output=True, timeout=30)
            
            if extract_dir.exists():
                # 1. Buscar .desktop
                desktop_files = list(extract_dir.rglob("*.desktop"))
                selected_desktop = None
                for df in desktop_files:
                    try:
                        if df.exists() and df.is_file():
                            selected_desktop = df
                            break
                    except: continue
                
                if selected_desktop:
                    with open(selected_desktop, "r", errors="ignore") as f:
                        for line in f:
                            if line.startswith("Name="): app_name = line.split("=", 1)[1].strip()
                            elif line.startswith("Comment="): description = line.split("=", 1)[1].strip()
                            elif line.startswith("Icon="): icon_source = line.split("=", 1)[1].strip()
                
                # 2. Buscar Icono
                icon_file = None
                
                # Prioridad 1: .DirIcon
                dir_icon = extract_dir / ".DirIcon"
                if dir_icon.exists():
                    icon_file = dir_icon
                
                # Prioridad 2: Buscar archivos que coincidan con icon_source (recursivo y case-insensitive)
                if not icon_file or not icon_file.exists():
                    all_images = list(extract_dir.rglob("*.png")) + list(extract_dir.rglob("*.svg")) + list(extract_dir.rglob("*.ico"))
                    search_pattern = icon_source.lower()
                    for img in all_images:
                        if search_pattern == img.stem.lower():
                            icon_file = img
                            break
                    
                    # Si no hay coincidencia exacta del nombre, buscar coincidencia parcial
                    if not icon_file:
                        for img in all_images:
                            if search_pattern in img.name.lower():
                                icon_file = img
                                break
                
                # Prioridad 3: Cualquier imagen que parezca un icono de app
                if not icon_file or not icon_file.exists():
                    for img in all_images:
                        if "icon" in img.name.lower() or img.name.lower().startswith(app_name.lower()):
                            icon_file = img
                            break

                if icon_file and icon_file.exists():
                    ext = icon_file.suffix if icon_file.suffix else ".png"
                    target_icon = opt_dir / f"icon{ext}"
                    shutil.copy2(icon_file, target_icon)
                    icon_source = str(target_icon)
    except Exception as e:
        print(f"Warning: Could not extract metadata: {e}")

    desktop_content = f"""[Desktop Entry]
Name={app_name}
Comment={description}
Exec="{target_path}"
Icon={icon_source}
Type=Application
Categories=Utility;
Terminal=false
X-Wakka-Installed=true
"""
    desktop_path = Path("/usr/share/applications") / f"{raw_name}.desktop"
    with open(desktop_path, "w") as f:
        f.write(desktop_content)
    
    print(f"--- AppImage installed: {app_name} ---")
    return True

if __name__ == "__main__":
    if len(sys.argv) < 3:
        sys.exit(1)
        
    action = sys.argv[1]
    file_path = sys.argv[2]
    
    try:
        if action == "convert":
            result = convert_to_arch(file_path)
            if result:
                print(f"RESULT:{result}")
        elif action == "appimage":
            install_appimage(file_path)
    except Exception as e:
        print(f"Error: {e}")
        sys.exit(1)
